### ISSUE TITLE
SOLOv2.py Can there be more detailed code comments

### ISSUE THREAD

**Issue by xiaoyaod** [clovaai/PointWSSIS#1]
Your work is fantastic

**Comment by qjadud1994** [comment]
We appreciate your interest in our work.
Most of our implementation is in [here](https://github.com/clovaai/PointWSSIS/blob/bd3156e3866ac9131187f50cd0ee0cd0c2513589/AdelaiDet/adet/modeling/solov2/solov2.py#L154-L253).

We recommend that you first understand the SOLOv2 implementation before following our implementation.
