### ISSUE TITLE
Performance in Figure 6.

### ISSUE THREAD

**Issue by linyq2117** [clovaai/PointWSSIS#4]
Hi, this is an excellent work, thanks for sharing.

I have a question about Figure 6 in your paper. I use the provided teacher network ckpt to evaluate on COCO 2017 validation set, but the results are not consistent with the `Full label setting` in Figure 6. I got 12.38%AP when using COCO 1% subset and 30.58%AP for COCO 5% subset, which are significantly better than the reported results in Figure 6.  Are there some specific configures to notice when evaluating the teacher model?  

Thanks for your reading and I'm looking forward to your reply.

**Comment by qjadud1994** [comment]
Thank you for your interest in our work.

I need more detailed information about your experiment, but I think the better performance of the teacher network may arise from the `MODEL.SOLOV2.PROMPT` option. When evaluating the performance of the teacher network, you should set `MODEL.SOLOV2.PROMPT none`.

`MODEL.SOLOV2.PROMPT point` means using GT point labels during the inference stage.

**Comment by linyq2117** [comment]
Thanks for your reply.

It seems that the config of the teacher model is not strictly consistent with the original SOLOv2. I try to use the latter to realize the `Full label setting` now. By the way, can you share the `COCO train5K` split file used in the paper?

**Comment by qjadud1994** [comment]
I uploaded it to Google-Drive (https://drive.google.com/file/d/1ZoaW7L_LAnIlVCD2sFJgB2IPbWbpTgys/view?usp=drive_link).

**Comment by linyq2117** [comment]
Thanks a lot!
