### ISSUE TITLE
What is the procedure to train on our own coco format dataset

### ISSUE THREAD

**Issue by theCuriousDev1** [clovaai/PointWSSIS#5]
Hello, 

congrats on this awesome work!.

Can you guys explain how do we train this network for our own coco format instance segmentation dataset? 

I was trying to understand the flow from your provided scripts. Since there are no comments I could not understand.. 

Would be awesome if you can explain at-least one of the scripts. may be [coco_10p.sh](https://github.com/clovaai/PointWSSIS/blob/main/scripts/coco_10p.sh)?

**Comment by qjadud1994** [comment]
Thank you for your interest in our work.

1. First, you should understand the process of the ground-truth label generation implementation ([get_ground_truth_single function](https://github.com/clovaai/PointWSSIS/blob/bd3156e3866ac9131187f50cd0ee0cd0c2513589/AdelaiDet/adet/modeling/solov2/solov2.py#L281)].

2. In the `def get_ground_truth_single(self, img_idx, gt_instances, mask_feat_size)` function, `gt_instances` contains all information about the ground-truth instances, including instance masks, bounding boxes, labels, sizes, etc. This function encodes the `gt_instances` to the valid format for the SOLO-V2 network. When encoding, we also obtain point information extracted from instance masks (the centroid point of an instance mask). If you have your own point labels, please replace this part to directly use the point labels.

3. Moreover, during inference for generating pseudo labels using point labels, the point prompting can be simply replaced with using `cate_gt` as shown [here](https://github.com/clovaai/PointWSSIS/blob/bd3156e3866ac9131187f50cd0ee0cd0c2513589/AdelaiDet/adet/modeling/solov2/solov2.py#L240-L249).

4. Actually, our repository is implemented to be compatible with the SOLO-V2 code. Therefore, before following our work, we recommend that you first understand the mechanism of SOLO-V2.
